name = "Elegancia"
license = "MIT"
licenselink = "https://github.com/krlade/hugo-elegancia/blob/master/LICENSE"
description = "A simple hugo theme for blogging and personal website"

homepage = "https://github.com/krlade/hugo-elegancia"
demosite = "https://karol.lademan.dev"

tags = ["blog", "clean", "dark", "personal", "link tree"]
features = ["fast", "simple"]

min_version = "0.87.0"

[author]
  name = "Karol Lademan"
  homepage = "https://karol.lademan.dev"
